// <auto-generated />
using System;
using LicenseGenerator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseGenerator.Api.Data.Migrations
{
    [DbContext(typeof(LicenseGeneratorContext))]
    partial class LicenseGeneratorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LicenseGenerator.Api.Models.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.Device", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.HasKey("SerialNumber");

                    b.HasIndex("ModelID");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.DeviceModels", b =>
                {
                    b.Property<string>("ModelId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.ToTable("DeviceModel", (string)null);
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceID")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DealerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.InvoiceDeviceMapping", b =>
                {
                    b.Property<string>("InvoiceID")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceSerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InvoiceID", "SerialNumber");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("InvoiceDeviceMappings", (string)null);
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.License", b =>
                {
                    b.Property<string>("LicenseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ActivationDate")
                        .HasColumnType("date");

                    b.Property<string>("ActivationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseID");

                    b.HasIndex("DeviceSerialNumber");

                    b.HasIndex("InvoiceID");

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.Device", b =>
                {
                    b.HasOne("LicenseGenerator.Api.Models.DeviceModels", "Model")
                        .WithMany("Devices")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.Invoice", b =>
                {
                    b.HasOne("LicenseGenerator.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.InvoiceDeviceMapping", b =>
                {
                    b.HasOne("LicenseGenerator.Api.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber");

                    b.HasOne("LicenseGenerator.Api.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.License", b =>
                {
                    b.HasOne("LicenseGenerator.Api.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber");

                    b.HasOne("LicenseGenerator.Api.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LicenseGenerator.Api.Models.DeviceModels", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
